cmake_minimum_required(VERSION 3.14)
project(Deckerz LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)

file(GLOB_RECURSE SOURCES
    ${CMAKE_CURRENT_SOURCE_DIR}/src/*.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/*.hpp
)
add_executable(Deckerz ${SOURCES})
target_compile_definitions(Deckerz PRIVATE $<$<CONFIG:Debug>:DEBUG>)

# SFML is deprecated
# target_link_libraries(Deckerz PRIVATE sfml-system sfml-window sfml-graphics sfml-network sfml-audio)
target_link_libraries(Deckerz PRIVATE raylib)
target_include_directories(Deckerz PRIVATE src)

add_custom_command(
    TARGET Deckerz
    POST_BUILD
    COMMAND ${CMAKE_COMMAND} -E remove_directory
            "$<TARGET_FILE_DIR:Deckerz>/res"
    COMMAND ${CMAKE_COMMAND} -E copy_directory
            "${CMAKE_CURRENT_SOURCE_DIR}/res"
            "$<TARGET_FILE_DIR:Deckerz>/res"
)